'use client'

import { useState, useEffect } from 'react'
import { FormField } from '@/lib/types'
import { X, Plus, Trash2, Copy, Eye, EyeOff, AlertTriangle, CheckCircle, Lightbulb } from 'lucide-react'
import DynamicListConfig from './DynamicListConfig'
import { 
  validateFieldName, 
  sanitizeFieldName, 
  generateFieldName, 
  isFieldNameUnique,
  labelToFieldName 
} from '@/lib/field-name-utils'
import FieldNamePreview from './FieldNamePreview'
import FieldNameGuide from './FieldNameGuide'
import CalculatedFieldConfig from './CalculatedFieldConfig'

interface FieldPropertiesProps {
  field: FormField | null
  onFieldUpdate: (field: FormField) => void
  onFieldDelete: (fieldId: string) => void
  onFieldDuplicate: (field: FormField) => void
  onClose: () => void
  allFields?: FormField[] // Para verificar nomes únicos
  showSuccess?: (title: string, message: string) => void
}

export default function FieldProperties({ 
  field, 
  onFieldUpdate, 
  onFieldDelete, 
  onFieldDuplicate,
  onClose,
  allFields = [],
  showSuccess
}: FieldPropertiesProps) {
  const [editedField, setEditedField] = useState<FormField | null>(null)
  const [options, setOptions] = useState<string[]>([])
  const [showAdvanced, setShowAdvanced] = useState(false)
  const [fieldNameValidation, setFieldNameValidation] = useState<{
    isValid: boolean
    errors: string[]
    suggestions: string[]
  }>({ isValid: true, errors: [], suggestions: [] })
  const [autoGenerateName, setAutoGenerateName] = useState(true)

  // 🔧 Função inteligente para determinar se deve mostrar correção de nome
  const shouldShowNameCorrection = (field: FormField): boolean => {
    if (!field || !field.name || !field.id) return false
    
    // 1. Se o nome já está em formato válido snake_case, NÃO mostrar correção
    const hasValidFormat = /^[a-z][a-z0-9_]*$/.test(field.name)
    const isReasonableLength = field.name.length <= 50
    
    // 2. Se o nome foi sanitizado corretamente do label, NÃO mostrar correção
    const expectedFromLabel = sanitizeFieldName(field.label || '')
    const isBasedOnLabel = field.name.startsWith(expectedFromLabel) || field.name === expectedFromLabel
    
    // 3. Se o nome não tem caracteres problemáticos, NÃO mostrar correção
    const hasProblematicChars = /[^a-z0-9_]/.test(field.name)
    
    // 4. Se o campo foi corrigido recentemente (nome válido), NÃO mostrar
    if (hasValidFormat && isReasonableLength && !hasProblematicChars) {
      console.log('✅ Campo com nome válido, não mostrando correção:', field.name)
      return false
    }
    
    // 5. Verificar se é um ID muito longo gerado automaticamente
    const isAutoGeneratedId = field.name.includes('_') && field.name.length > 30
    const hasTimestamp = /\d{6,}/.test(field.name)
    
    // Só mostrar correção se há problemas REAIS
    const shouldShow = hasProblematicChars || (isAutoGeneratedId && hasTimestamp)
    
    console.log('🔍 Verificação de correção:', {
      fieldName: field.name,
      hasValidFormat,
      isReasonableLength,
      hasProblematicChars,
      isAutoGeneratedId,
      hasTimestamp,
      shouldShow
    })
    
    return shouldShow
  }

  const validateAndUpdateFieldName = (name: string) => {
    const existingNames = allFields
      .filter(f => f.id !== editedField?.id)
      .map(f => f.name.toLowerCase())
    
    const validation = validateFieldName(name)
    const isUnique = isFieldNameUnique(name, existingNames, editedField?.id, allFields)
    
    if (!isUnique) {
      validation.isValid = false
      validation.errors.push('Nome já existe em outro campo')
      validation.suggestions.push('Escolha um nome único')
    }
    
    setFieldNameValidation(validation)
    return validation.isValid
  }

  useEffect(() => {
    if (field) {
      setEditedField({ ...field })
      setOptions(field.options || [])
      
      // Validar nome do campo inicial
      if (field.name) {
        validateAndUpdateFieldName(field.name)
      }
      
      // Verificar se o nome foi gerado automaticamente
      const expectedName = labelToFieldName(field.label)
      setAutoGenerateName(field.name === expectedName || !field.name)
      
      // Log para debug
      console.log('🔍 Verificando campo:', {
        id: field.id,
        name: field.name,
        label: field.label,
        shouldShowCorrection: shouldShowNameCorrection(field)
      })
    }
  }, [field?.id, field?.name]) // Incluir field.name para reagir a mudanças

  // Validação separada quando allFields muda
  useEffect(() => {
    if (editedField?.name) {
      validateAndUpdateFieldName(editedField.name)
    }
  }, [allFields.length]) // Apenas quando o número de campos muda

  if (!editedField) return null

  const handleSave = () => {
    if (!editedField) return
    
    const updatedField = {
      ...editedField,
      options: editedField.type === 'select' ? options.filter(opt => opt.trim()) : undefined
    }
    
    console.log('💾 Salvando propriedades do campo:', updatedField)
    onFieldUpdate(updatedField)
    onClose()
  }

  const handleFieldChange = (key: keyof FormField, value: any) => {
    if (!editedField) return
    
    // Nome do campo não é mais editável - ignorar mudanças no nome
    if (key === 'name') {
      return
    }
    
    let newField = { ...editedField, [key]: value }
    
    setEditedField(newField)
    
    // Atualizar em tempo real
    const updatedField = {
      ...newField,
      options: newField.type === 'select' ? options.filter(opt => opt.trim()) : undefined
    }
    
    onFieldUpdate(updatedField)
  }

  const handlePositionChange = (key: keyof FormField['position'], value: number) => {
    const newField = editedField ? {
      ...editedField,
      position: { ...editedField.position, [key]: value }
    } : null
    
    setEditedField(newField)
    
    // Atualizar em tempo real
    if (newField) {
      onFieldUpdate(newField)
    }
  }

  const handleAlignmentChange = (
    type: 'horizontal' | 'vertical', 
    value: 'left' | 'center' | 'right' | 'top' | 'middle' | 'bottom'
  ) => {
    if (!editedField) return
    
    const currentAlignment = editedField.alignment || {
      horizontal: 'left',
      vertical: 'middle'
    }
    
    const newAlignment = {
      ...currentAlignment,
      [type]: value
    }
    
    const newField = {
      ...editedField,
      alignment: newAlignment
    }
    
    setEditedField(newField)
    
    // Atualizar em tempo real
    onFieldUpdate(newField)
  }

  const handleFontStyleChange = (property: string, value: any) => {
    if (!editedField) return
    
    const currentFontStyle = editedField.fontStyle || {
      family: 'Arial',
      size: 12,
      weight: 'normal',
      style: 'normal',
      decoration: 'none',
      color: '#000000'
    }
    
    const newFontStyle = {
      ...currentFontStyle,
      [property]: value
    }
    
    const newField = {
      ...editedField,
      fontStyle: newFontStyle
    }
    
    setEditedField(newField)
    
    // Atualizar em tempo real
    onFieldUpdate(newField)
  }

  const handleValidationChange = (key: string, value: any) => {
    const newField = editedField ? {
      ...editedField,
      validation: { ...editedField.validation, [key]: value }
    } : null
    
    setEditedField(newField)
    
    // Atualizar em tempo real
    if (newField) {
      onFieldUpdate(newField)
    }
  }

  const addOption = () => {
    setOptions([...options, ''])
  }

  const updateOption = (index: number, value: string) => {
    const newOptions = [...options]
    newOptions[index] = value
    setOptions(newOptions)
  }

  const removeOption = (index: number) => {
    setOptions(options.filter((_, i) => i !== index))
  }

  const fieldTypes = [
    { value: 'text', label: 'Texto', icon: '📝' },
    { value: 'number', label: 'Número', icon: '🔢' },
    { value: 'calculated', label: 'Calculado', icon: '🧮' },
    { value: 'date', label: 'Data', icon: '📅' },
    { value: 'textarea', label: 'Área de Texto', icon: '📄' },
    { value: 'select', label: 'Lista de Seleção', icon: '📋' },
    { value: 'dynamic_list', label: 'Lista Dinâmica', icon: '🔗' },
    { value: 'checkbox', label: 'Checkbox', icon: '☑️' },
    { value: 'image', label: 'Imagem', icon: '🖼️' },
    { value: 'signature', label: 'Assinatura', icon: '✍️' }
  ]

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b">
          <div className="flex items-center space-x-3">
            <h3 className="text-lg font-semibold">Propriedades do Campo</h3>
            <span className="px-2 py-1 bg-gray-100 rounded text-xs font-medium">
              {editedField.type}
            </span>
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={() => onFieldDuplicate(editedField)}
              className="p-2 text-gray-400 hover:text-gray-600"
              title="Duplicar Campo"
            >
              <Copy className="h-4 w-4" />
            </button>
            <button
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-600"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          {/* Informações Básicas - Layout Vertical */}
          <div className="space-y-6">
            {/* Nome do Campo */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Nome do Campo (Banco de Dados)
              </label>
              <div className="relative">
                {/* Campo SEMPRE não editável para evitar quebras no sistema */}
                <div className="input-field bg-gray-50 text-gray-700 pr-8 flex items-center h-12">
                  <span className="flex-1 font-mono text-base">{editedField.name}</span>
                  <div className="flex items-center space-x-1">
                    <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded">Fixo</span>
                    <CheckCircle className="h-4 w-4 text-green-500" />
                  </div>
                </div>
              </div>
              
              <div className="flex items-center justify-between mt-2">
                <p className="text-xs text-green-600 flex items-center space-x-1">
                  <CheckCircle className="h-3 w-3" />
                  <span>Nome fixo na tabela PostgreSQL - não editável para evitar quebras</span>
                </p>
              </div>

              {/* Botão de correção forçada - só mostrar se realmente há problema */}
              {shouldShowNameCorrection(editedField) && (
                <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg">
                  <div className="flex items-start space-x-2">
                    <AlertTriangle className="h-4 w-4 text-red-500 mt-0.5" />
                    <div className="flex-1">
                      <p className="text-sm font-medium text-red-800 mb-2">
                        Nome incorreto detectado!
                      </p>
                      <p className="text-xs text-red-700 mb-3">
                        Nome atual: <code className="bg-red-100 px-1 rounded">{editedField.name}</code><br/>
                        Nome sugerido: <code className="bg-green-100 px-1 rounded">{sanitizeFieldName(editedField.label || editedField.name)}</code>
                      </p>
                      <button
                        onClick={() => {
                          const suggestedName = sanitizeFieldName(editedField.label || editedField.name)
                          const correctedField = { ...editedField, name: suggestedName }
                          setEditedField(correctedField)
                          onFieldUpdate(correctedField)
                          
                          // Mostrar mensagem de sucesso
                          if (showSuccess) {
                            showSuccess('Nome Corrigido', `Campo renomeado para "${suggestedName}"`)
                          }
                        }}
                        className="px-3 py-1 bg-red-600 text-white text-xs rounded hover:bg-red-700"
                      >
                        🔧 Corrigir Agora
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* Preview do nome na tabela */}
              <FieldNamePreview 
                fieldName={editedField.name}
                fieldType={editedField.type}
                isValid={fieldNameValidation.isValid}
              />

              {/* Guia de nomes de campos */}
              <FieldNameGuide />
            </div>

            {/* Label do Campo */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Label (Rótulo)
              </label>
              <input
                type="text"
                value={editedField.label}
                onChange={(e) => handleFieldChange('label', e.target.value)}
                className="input-field h-12 text-base"
                placeholder="Texto exibido para o usuário final"
              />
              <p className="text-xs text-gray-500 mt-1">
                Texto exibido para o usuário final
              </p>
            </div>
          </div>

          {/* Tipo do Campo */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Tipo do Campo
            </label>
            <div className="grid grid-cols-4 gap-2">
              {fieldTypes.map(type => (
                <button
                  key={type.value}
                  onClick={() => handleFieldChange('type', type.value)}
                  className={`p-3 rounded-lg border text-center transition-colors ${
                    editedField.type === type.value
                      ? 'border-primary-500 bg-primary-50 text-primary-700'
                      : 'border-gray-200 hover:border-gray-300'
                  }`}
                >
                  <div className="text-lg mb-1">{type.icon}</div>
                  <div className="text-xs font-medium">{type.label}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Configurações do Campo */}
          <div className="grid grid-cols-2 gap-4">
            <div className="flex items-center">
              <input
                type="checkbox"
                id="required"
                checked={editedField.required}
                onChange={(e) => handleFieldChange('required', e.target.checked)}
                className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
              />
              <label htmlFor="required" className="ml-2 block text-sm text-gray-900">
                Campo obrigatório
              </label>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Placeholder
              </label>
              <input
                type="text"
                value={editedField.placeholder || ''}
                onChange={(e) => handleFieldChange('placeholder', e.target.value)}
                className="input-field h-12 text-base"
                placeholder="Texto de exemplo..."
              />
            </div>
          </div>

          {/* Texto de Ajuda */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Texto de Ajuda
            </label>
            <textarea
              value={editedField.helpText || ''}
              onChange={(e) => handleFieldChange('helpText', e.target.value)}
              className="input-field text-base"
              rows={3}
              placeholder="Instruções ou dicas para o usuário..."
            />
          </div>

          {/* Opções para Select */}
          {editedField.type === 'select' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Opções da Lista
              </label>
              <div className="space-y-2">
                {options.map((option, index) => (
                  <div key={index} className="flex items-center space-x-2">
                    <input
                      type="text"
                      value={option}
                      onChange={(e) => updateOption(index, e.target.value)}
                      placeholder={`Opção ${index + 1}`}
                      className="input-field flex-1"
                    />
                    <button
                      onClick={() => removeOption(index)}
                      className="p-2 text-red-500 hover:text-red-700"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                ))}
                <button
                  onClick={addOption}
                  className="flex items-center space-x-1 text-primary-600 hover:text-primary-700"
                >
                  <Plus className="h-4 w-4" />
                  <span>Adicionar Opção</span>
                </button>
              </div>
            </div>
          )}

          {/* Configuração para Lista Dinâmica */}
          {editedField.type === 'dynamic_list' && (
            <DynamicListConfig
              field={editedField}
              onUpdate={(updatedField) => setEditedField(updatedField)}
            />
          )}

          {/* Configuração para Campo Calculado */}
          {editedField.type === 'calculated' && (
            <CalculatedFieldConfig
              field={editedField}
              allFields={allFields}
              currentValues={{}} // Valores atuais dos campos (pode ser expandido)
              onUpdate={(updates) => {
                const updatedField = { ...editedField, ...updates }
                setEditedField(updatedField)
                // IMPORTANTE: Salvar no banco através do onFieldUpdate
                onFieldUpdate(updatedField)
                if (showSuccess) {
                  showSuccess('Campo Calculado', 'Configuração salva com sucesso!')
                }
              }}
              onClose={onClose} // Fechar o FieldProperties quando cancelar
            />
          )}

          {/* Validação para Number */}
          {editedField.type === 'number' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Validação Numérica
              </label>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs text-gray-600 mb-1">
                    Valor Mínimo
                  </label>
                  <input
                    type="number"
                    value={editedField.validation?.min || ''}
                    onChange={(e) => handleValidationChange('min', e.target.value ? Number(e.target.value) : undefined)}
                    className="input-field"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-600 mb-1">
                    Valor Máximo
                  </label>
                  <input
                    type="number"
                    value={editedField.validation?.max || ''}
                    onChange={(e) => handleValidationChange('max', e.target.value ? Number(e.target.value) : undefined)}
                    className="input-field"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Validação para Text */}
          {editedField.type === 'text' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Validação de Texto
              </label>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs text-gray-600 mb-1">
                    Comprimento Máximo
                  </label>
                  <input
                    type="number"
                    value={editedField.validation?.maxLength || ''}
                    onChange={(e) => handleValidationChange('maxLength', e.target.value ? Number(e.target.value) : undefined)}
                    className="input-field"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-600 mb-1">
                    Padrão (Regex)
                  </label>
                  <input
                    type="text"
                    value={editedField.validation?.pattern || ''}
                    onChange={(e) => handleValidationChange('pattern', e.target.value)}
                    className="input-field"
                    placeholder="^[A-Za-z]+$"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Configurações Avançadas */}
          <div>
            <button
              onClick={() => setShowAdvanced(!showAdvanced)}
              className="flex items-center space-x-2 text-sm text-gray-600 hover:text-gray-800"
            >
              {showAdvanced ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              <span>Configurações Avançadas</span>
            </button>

            {showAdvanced && (
              <div className="mt-4 p-4 bg-gray-50 rounded-lg space-y-4">
                <div className="grid grid-cols-4 gap-4">
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">X</label>
                    <input
                      type="number"
                      value={editedField.position.x}
                      onChange={(e) => handlePositionChange('x', Number(e.target.value))}
                      className="input-field text-sm"
                    />
                  </div>
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">Y</label>
                    <input
                      type="number"
                      value={editedField.position.y}
                      onChange={(e) => handlePositionChange('y', Number(e.target.value))}
                      className="input-field text-sm"
                    />
                  </div>
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">Largura</label>
                    <input
                      type="number"
                      value={editedField.position.width}
                      onChange={(e) => handlePositionChange('width', Number(e.target.value))}
                      className="input-field text-sm"
                    />
                  </div>
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">Altura</label>
                    <input
                      type="number"
                      value={editedField.position.height}
                      onChange={(e) => handlePositionChange('height', Number(e.target.value))}
                      className="input-field text-sm"
                    />
                  </div>
                </div>

                {/* Controles de Alinhamento do Conteúdo */}
                <div className="border-t pt-4">
                  <h4 className="text-sm font-medium text-gray-700 mb-3">Alinhamento do Conteúdo</h4>
                  
                  <div className="grid grid-cols-2 gap-4">
                    {/* Alinhamento Horizontal */}
                    <div>
                      <label className="block text-xs text-gray-600 mb-2">Horizontal</label>
                      <div className="flex space-x-1">
                        {[
                          { value: 'left', label: 'Esquerda', icon: '←' },
                          { value: 'center', label: 'Centro', icon: '↔' },
                          { value: 'right', label: 'Direita', icon: '→' }
                        ].map(option => (
                          <button
                            key={option.value}
                            onClick={() => handleAlignmentChange('horizontal', option.value as 'left' | 'center' | 'right')}
                            className={`flex-1 px-2 py-1 text-xs rounded border transition-colors ${
                              (editedField.alignment?.horizontal || 'left') === option.value
                                ? 'border-blue-500 bg-blue-50 text-blue-700'
                                : 'border-gray-200 hover:border-gray-300'
                            }`}
                            title={option.label}
                          >
                            {option.icon}
                          </button>
                        ))}
                      </div>
                    </div>

                    {/* Alinhamento Vertical */}
                    <div>
                      <label className="block text-xs text-gray-600 mb-2">Vertical</label>
                      <div className="flex space-x-1">
                        {[
                          { value: 'top', label: 'Topo', icon: '↑' },
                          { value: 'middle', label: 'Meio', icon: '↕' },
                          { value: 'bottom', label: 'Base', icon: '↓' }
                        ].map(option => (
                          <button
                            key={option.value}
                            onClick={() => handleAlignmentChange('vertical', option.value as 'top' | 'middle' | 'bottom')}
                            className={`flex-1 px-2 py-1 text-xs rounded border transition-colors ${
                              (editedField.alignment?.vertical || 'middle') === option.value
                                ? 'border-green-500 bg-green-50 text-green-700'
                                : 'border-gray-200 hover:border-gray-300'
                            }`}
                            title={option.label}
                          >
                            {option.icon}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>

                  <p className="text-xs text-gray-500 mt-2">
                    Define como o texto será posicionado dentro do campo no formulário e no PDF
                  </p>
                </div>

                {/* Controles de Formatação de Fonte */}
                <div className="border-t pt-4">
                  <h4 className="text-sm font-medium text-gray-700 mb-3">Formatação de Fonte</h4>
                  
                  <div className="grid grid-cols-2 gap-4">
                    {/* Família e Tamanho */}
                    <div>
                      <label className="block text-xs text-gray-600 mb-2">Família da Fonte</label>
                      <select
                        value={editedField.fontStyle?.family || 'Arial'}
                        onChange={(e) => handleFontStyleChange('family', e.target.value)}
                        className="w-full text-xs border border-gray-300 rounded px-2 py-1"
                      >
                        <option value="Arial">Arial</option>
                        <option value="Helvetica">Helvetica</option>
                        <option value="Times">Times</option>
                        <option value="Courier">Courier</option>
                        <option value="Georgia">Georgia</option>
                        <option value="Verdana">Verdana</option>
                        <option value="Tahoma">Tahoma</option>
                      </select>
                    </div>

                    <div>
                      <label className="block text-xs text-gray-600 mb-2">Tamanho</label>
                      <input
                        type="number"
                        value={editedField.fontStyle?.size || 12}
                        onChange={(e) => handleFontStyleChange('size', parseInt(e.target.value) || 12)}
                        className="w-full text-xs border border-gray-300 rounded px-2 py-1"
                        min="8"
                        max="72"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-4 mt-3">
                    {/* Peso da Fonte */}
                    <div>
                      <label className="block text-xs text-gray-600 mb-2">Peso</label>
                      <select
                        value={editedField.fontStyle?.weight || 'normal'}
                        onChange={(e) => handleFontStyleChange('weight', e.target.value)}
                        className="w-full text-xs border border-gray-300 rounded px-2 py-1"
                      >
                        <option value="normal">Normal</option>
                        <option value="bold">Negrito</option>
                        <option value="lighter">Mais Leve</option>
                        <option value="bolder">Mais Pesado</option>
                      </select>
                    </div>

                    {/* Estilo da Fonte */}
                    <div>
                      <label className="block text-xs text-gray-600 mb-2">Estilo</label>
                      <select
                        value={editedField.fontStyle?.style || 'normal'}
                        onChange={(e) => handleFontStyleChange('style', e.target.value)}
                        className="w-full text-xs border border-gray-300 rounded px-2 py-1"
                      >
                        <option value="normal">Normal</option>
                        <option value="italic">Itálico</option>
                        <option value="oblique">Oblíquo</option>
                      </select>
                    </div>

                    {/* Decoração */}
                    <div>
                      <label className="block text-xs text-gray-600 mb-2">Decoração</label>
                      <select
                        value={editedField.fontStyle?.decoration || 'none'}
                        onChange={(e) => handleFontStyleChange('decoration', e.target.value)}
                        className="w-full text-xs border border-gray-300 rounded px-2 py-1"
                      >
                        <option value="none">Nenhuma</option>
                        <option value="underline">Sublinhado</option>
                        <option value="overline">Sobrelinha</option>
                        <option value="line-through">Riscado</option>
                      </select>
                    </div>
                  </div>

                  <div className="mt-3">
                    <label className="block text-xs text-gray-600 mb-2">Cor da Fonte</label>
                    <div className="flex items-center space-x-2">
                      <input
                        type="color"
                        value={editedField.fontStyle?.color || '#000000'}
                        onChange={(e) => handleFontStyleChange('color', e.target.value)}
                        className="w-12 h-8 border border-gray-300 rounded cursor-pointer"
                      />
                      <input
                        type="text"
                        value={editedField.fontStyle?.color || '#000000'}
                        onChange={(e) => handleFontStyleChange('color', e.target.value)}
                        className="flex-1 text-xs border border-gray-300 rounded px-2 py-1 font-mono"
                        placeholder="#000000"
                      />
                    </div>
                  </div>

                  <p className="text-xs text-gray-500 mt-2">
                    Define a aparência do texto no formulário e no PDF
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-6 border-t bg-gray-50">
          <button
            onClick={() => onFieldDelete(editedField.id)}
            className="flex items-center space-x-2 text-red-600 hover:text-red-700"
          >
            <Trash2 className="h-4 w-4" />
            <span>Excluir Campo</span>
          </button>
          
          <div className="flex space-x-3">
            <button onClick={onClose} className="btn-secondary">
              Cancelar
            </button>
            <button onClick={handleSave} className="btn-primary">
              Salvar Alterações
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}